version: '3'

services:  
  db:
    image: "postgres:11"
    environment:
      - POSTGRES_USER=andrew
      - POSTGRES_PASSWORD=260062
      - POSTGRES_DB=mydb
    ports:
      - "5432:5432"
    volumes:
      - ./postgres-data:/var/lib/postgresql/data

  # service:
  #   build: .
  #   volumes:
  #     - .:/usr/src/app
  #     - /usr/src/app/node_modules
  #   ports:
  #     - "4001:4001"
  #   links:
  #     - db
  #   depends_on:
  #     - db