name: Node CI

on: [push]

jobs:
  Install:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: 12.x

    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: npm install, build, and test
      run: |
        yarn
      env:
        CI: true

  Lint:
    needs: Install
    runs-on: ubuntu-latest
    steps:
      - uses: actions/download-artifact@v1
        with:
          node-version: 12.x
      - name: Check types and lint
      run: |
        yarn tsc --noEmit
        yarn eslint
