name: Pull-Requests Check

on:
  pull_request:
    branches:
      - master
  push:
    branches:
      - master

jobs:

  Frontend_Lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
        with:
          node-version: 12
      - run: cd client && yarn && yarn eslint && yarn tsc

  Frontend_Coverage:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
        with:
          node-version: 12
      - run: cd client && yarn && yarn coverage

  Backend_Lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
        with:
          node-version: 12
      - run: cd backend && yarn && yarn lint
